CREATE TABLE dbo.DeliveryAddress
(
  Id INT NOT NULL IDENTITY,
  UserId NVARCHAR(256) NOT NULL,
  AddressType NVARCHAR(50) NOT NULL,
  Name NVARCHAR(50) NOT NULL,
  StreetAddress NVARCHAR(50) NOT NULL,
  City NVARCHAR(50) NOT NULL,
  State NVARCHAR(2) NOT NULL,
  ZipCode NVARCHAR(5) NOT NULL,
  PhoneNumber NVARCHAR(MAX) NOT NULL,
  PRIMARY KEY (Id),
  CONSTRAINT FK_DeliveryAddress_SiteUser FOREIGN KEY (UserId) REFERENCES SiteUser(Id)
)