CREATE TABLE dbo.MenuPizzaCrust
(
  Id INT NOT NULL IDENTITY,
  SortOrder INT NOT NULL,
  AvailableForPurchase BIT NOT NULL,
  Name NVARCHAR(100) NOT NULL,
  PriceSmall DECIMAL(20,2) NOT NULL,
  PriceMedium DECIMAL(20,2) NOT NULL,
  PriceLarge DECIMAL(20,2) NOT NULL,
  Description NVARCHAR(512) NOT NULL,
  PRIMARY KEY (Id)
)