CREATE TABLE dbo.StoreLocation
(
  Id INT NOT NULL IDENTITY,
  Name NVARCHAR(50) NOT NULL,
  StreetAddress NVARCHAR(50) NOT NULL,
  City NVARCHAR(50) NOT NULL,
  State NVARCHAR(2) NOT NULL,
  ZipCode NVARCHAR(5) NOT NULL,
  PhoneNumber NVARCHAR(MAX) NOT NULL,
  IsActiveLocation BIT NOT NULL,
  PRIMARY KEY (Id)
)