CREATE TABLE dbo.UserRole
(
  Id INT NOT NULL IDENTITY,
  UserId INT NOT NULL,
  RoleId INT NOT NULL,
  PRIMARY KEY (Id),
  CONSTRAINT FK_UserRole_SiteUser FOREIGN KEY (UserId) REFERENCES SiteUser(Id),
  CONSTRAINT FK_UserRole_SiteRole FOREIGN KEY (RoleId) REFERENCES SiteRole(Id)
)