CREATE TABLE dbo.UserRole
(
  Id INT NOT NULL IDENTITY,
  UserId NVARCHAR(256) NOT NULL,
  RoleName NVARCHAR(256) NOT NULL,
  PRIMARY KEY (Id),
  CONSTRAINT FK_UserRole_SiteUser FOREIGN KEY (UserId) REFERENCES SiteUser(Id)
)