CREATE TABLE dbo.UserClaim
(
  Id INT NOT NULL IDENTITY,
  UserId INT NOT NULL,
  ClaimType NVARCHAR(MAX),
  ClaimValue NVARCHAR(MAX),
  PRIMARY KEY (Id),
  CONSTRAINT FK_UserClaim_SiteUser FOREIGN KEY (UserId) REFERENCES SiteUser(Id)
)